import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/common";

export const metadata: Metadata = {
  title: "Edu City",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
